// Generated by Scripts/build_configs.py. Do not edit manually.
// FlClash script override: apply this to an existing Clash/Mihomo subscription.
const main = (config) => {
  const managedGroups = [
  {
    "name": "📈 美股交易",
    "type": "select",
    "include-all": true
  },
  {
    "name": "🤖 AI",
    "type": "select",
    "include-all": true,
    "proxies": [
      "DIRECT"
    ]
  },
  {
    "name": "💻 GitHub",
    "type": "select",
    "include-all": true,
    "proxies": [
      "DIRECT"
    ]
  },
  {
    "name": "🌍 Google",
    "type": "select",
    "include-all": true,
    "proxies": [
      "DIRECT"
    ]
  },
  {
    "name": "📺 媒体",
    "type": "select",
    "include-all": true,
    "proxies": [
      "DIRECT"
    ]
  }
];
  const managedProviders = {
  "blackmatrix7-OpenAI": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml",
    "path": "./ruleset/blackmatrix7-OpenAI.yaml"
  },
  "blackmatrix7-Claude": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml",
    "path": "./ruleset/blackmatrix7-Claude.yaml"
  },
  "blackmatrix7-Gemini": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml",
    "path": "./ruleset/blackmatrix7-Gemini.yaml"
  },
  "blackmatrix7-GitHub": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml",
    "path": "./ruleset/blackmatrix7-GitHub.yaml"
  },
  "blackmatrix7-Google": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml",
    "path": "./ruleset/blackmatrix7-Google.yaml"
  },
  "blackmatrix7-YouTube": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml",
    "path": "./ruleset/blackmatrix7-YouTube.yaml"
  },
  "blackmatrix7-Netflix": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml",
    "path": "./ruleset/blackmatrix7-Netflix.yaml"
  },
  "blackmatrix7-Disney": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml",
    "path": "./ruleset/blackmatrix7-Disney.yaml"
  },
  "blackmatrix7-Apple": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml",
    "path": "./ruleset/blackmatrix7-Apple.yaml"
  },
  "blackmatrix7-China": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.yaml",
    "path": "./ruleset/blackmatrix7-China.yaml"
  },
  "blackmatrix7-Advertising": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml",
    "path": "./ruleset/blackmatrix7-Advertising.yaml"
  },
  "blackmatrix7-Privacy": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy.yaml",
    "path": "./ruleset/blackmatrix7-Privacy.yaml"
  }
};
  const managedRules = [
  "DOMAIN-SUFFIX,futunn.com,📈 美股交易",
  "DOMAIN-SUFFIX,futu5.com,📈 美股交易",
  "DOMAIN-SUFFIX,futuhk.com,📈 美股交易",
  "DOMAIN-SUFFIX,futuhh.com,📈 美股交易",
  "DOMAIN-SUFFIX,futustatic.com,📈 美股交易",
  "DOMAIN-SUFFIX,moomoo.com,📈 美股交易",
  "DOMAIN-SUFFIX,moomooapp.com,📈 美股交易",
  "DOMAIN-SUFFIX,longbridge.com,📈 美股交易",
  "DOMAIN-SUFFIX,longbridgeapp.com,📈 美股交易",
  "DOMAIN-SUFFIX,longportapp.com,📈 美股交易",
  "DOMAIN-SUFFIX,lbkrs.com,📈 美股交易",
  "DOMAIN-SUFFIX,longbridgehk.com,📈 美股交易",
  "DOMAIN-SUFFIX,cursor.com,🤖 AI",
  "DOMAIN-SUFFIX,cursor.sh,🤖 AI",
  "DOMAIN-SUFFIX,windsurf.com,🤖 AI",
  "DOMAIN-SUFFIX,codeium.com,🤖 AI",
  "DOMAIN-SUFFIX,githubcopilot.com,🤖 AI",
  "DOMAIN,copilot-proxy.githubusercontent.com,🤖 AI",
  "DOMAIN-SUFFIX,perplexity.ai,🤖 AI",
  "DOMAIN-SUFFIX,grok.com,🤖 AI",
  "DOMAIN-SUFFIX,x.ai,🤖 AI",
  "RULE-SET,blackmatrix7-OpenAI,🤖 AI",
  "RULE-SET,blackmatrix7-Claude,🤖 AI",
  "RULE-SET,blackmatrix7-Gemini,🤖 AI",
  "DOMAIN-SUFFIX,ghcr.io,💻 GitHub",
  "RULE-SET,blackmatrix7-GitHub,💻 GitHub",
  "RULE-SET,blackmatrix7-Google,🌍 Google",
  "RULE-SET,blackmatrix7-YouTube,📺 媒体",
  "RULE-SET,blackmatrix7-Netflix,📺 媒体",
  "RULE-SET,blackmatrix7-Disney,📺 媒体",
  "RULE-SET,blackmatrix7-Apple,DIRECT",
  "RULE-SET,blackmatrix7-China,DIRECT",
  "RULE-SET,blackmatrix7-Advertising,REJECT",
  "RULE-SET,blackmatrix7-Privacy,REJECT"
];

  const managedGroupNames = {};
  managedGroups.forEach((group) => {
    managedGroupNames[group.name] = true;
  });
  const originalGroups = Array.isArray(config["proxy-groups"])
    ? config["proxy-groups"]
    : [];
  config["proxy-groups"] = managedGroups.concat(
    originalGroups.filter((group) => !managedGroupNames[group.name]),
  );

  config["rule-providers"] = Object.assign(
    {},
    config["rule-providers"] || {},
    managedProviders,
  );

  const managedRuleNames = {};
  managedRules.forEach((rule) => {
    managedRuleNames[rule] = true;
  });
  const originalRules = Array.isArray(config.rules) ? config.rules : [];
  config.rules = managedRules.concat(
    originalRules.filter((rule) => !managedRuleNames[rule]),
  );
  return config;
};
