#!/usr/bin/env python3
"""Generate client configs from RuleSets/manifest.json and local rule lists."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml
from common import (
    ROOT,
    RULESETS,
    clash_url,
    load_manifest,
    parse_rule_file,
    provider_name,
    shadowrocket_url,
)

GENERATED_HEADER = "# Generated by Scripts/build_configs.py. Do not edit manually."
BUILTIN_POLICIES = {"DIRECT", "REJECT", "REJECT-DROP", "PASS", "PROXY"}


def yaml_text(data: Any, header: str = GENERATED_HEADER) -> str:
    rendered = yaml.safe_dump(data, allow_unicode=True, sort_keys=False, width=1000)
    return f"{header}\n{rendered}"


def module_rules(group: dict[str, Any]) -> list[str]:
    local_rules = parse_rule_file(RULESETS / group["local"])
    policy = group["policy"]
    rules = [f"{rule.text},{policy}" for rule in local_rules]
    rules.extend(f"RULE-SET,{shadowrocket_url(name)},{policy}" for name in group["upstream"])
    return rules


def clash_rules(group: dict[str, Any]) -> list[str]:
    local_rules = parse_rule_file(RULESETS / group["local"])
    policy = group["policy"]
    rules = [f"{rule.text},{policy}" for rule in local_rules]
    rules.extend(f"RULE-SET,{provider_name(name)},{policy}" for name in group["upstream"])
    return rules


def selectable_groups(groups: list[dict[str, Any]], client: str) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    for group in groups:
        if group["policy"] in BUILTIN_POLICIES:
            continue
        item: dict[str, Any] = {"name": group["policy"], "type": "select"}
        if client == "clash":
            item["include-all"] = True
            if group["id"] != "US-Trade":
                item["proxies"] = ["DIRECT"]
        else:
            item["proxies"] = ["🚀 节点选择", "DIRECT"]
        output.append(item)
    return output


def render_shadowrocket_module(group: dict[str, Any]) -> str:
    lines = [
        f"#!name={group['policy']} · {group['id']}",
        f"#!desc={group['description']}",
        GENERATED_HEADER,
        "",
        "[Rule]",
        *module_rules(group),
        "",
    ]
    return "\n".join(lines)


def render_shadowrocket_base(groups: list[dict[str, Any]]) -> str:
    group_lines = [
        "📈 美股交易 = select,PROXY,DIRECT",
        "🤖 AI = select,PROXY,DIRECT",
        "💻 GitHub = select,PROXY,DIRECT",
        "🌍 Google = select,PROXY,DIRECT",
        "📺 媒体 = select,PROXY,DIRECT",
        "🚀 通用代理 = select,PROXY,DIRECT",
    ]
    rules: list[str] = [
        f"RULE-SET,{shadowrocket_url('Lan')},DIRECT",
    ]
    for group in groups:
        rules.extend(module_rules(group))
    rules.extend(
        [
            f"RULE-SET,{shadowrocket_url('Proxy')},🚀 通用代理",
            "GEOIP,CN,DIRECT",
            "FINAL,🚀 通用代理",
        ]
    )
    return "\n".join(
        [
            GENERATED_HEADER,
            "",
            "[General]",
            "ipv6 = false",
            "dns-server = system,1.1.1.1,8.8.8.8",
            "skip-proxy = 127.0.0.1,localhost,*.local,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16",
            "",
            "[Proxy Group]",
            *group_lines,
            "",
            "[Rule]",
            *rules,
            "",
        ]
    )


def stash_override(group: dict[str, Any]) -> dict[str, Any]:
    data: dict[str, Any] = {
        "name": f"{group['policy']} · {group['id']}",
        "desc": group["description"],
    }
    if group["policy"] not in BUILTIN_POLICIES:
        data["proxy-groups"] = selectable_groups([group], "stash")
    data["rules"] = module_rules(group)
    return data


def all_stash_override(groups: list[dict[str, Any]]) -> dict[str, Any]:
    rules: list[str] = []
    for group in groups:
        rules.extend(module_rules(group))
    return {
        "name": "Proxy Modular Kit",
        "desc": "模块化策略组和高优先级规则；请按 README 替换上游节点组名",
        "proxy-groups": selectable_groups(groups, "stash"),
        "rules": rules,
    }


def clash_bundle(group: dict[str, Any]) -> dict[str, Any]:
    custom_groups = selectable_groups([group], "clash")
    return {
        "proxy-groups": {"prepend": custom_groups, "append": [], "delete": []},
        "rules": {"prepend": clash_rules(group), "append": [], "delete": []},
    }


def clash_merge(groups: list[dict[str, Any]]) -> dict[str, Any]:
    providers: dict[str, Any] = {}
    seen: set[str] = set()
    for group in groups:
        for upstream in group["upstream"]:
            if upstream in seen:
                continue
            seen.add(upstream)
            providers[provider_name(upstream)] = {
                "type": "http",
                "behavior": "classical",
                "format": "yaml",
                "interval": 86400,
                "url": clash_url(upstream),
                "path": f"./ruleset/{provider_name(upstream)}.yaml",
            }
    return {"rule-providers": providers}


def expected_outputs() -> dict[Path, str]:
    manifest = load_manifest()
    groups = manifest["groups"]
    outputs: dict[Path, str] = {
        ROOT / "Shadowrocket" / "Base.conf": render_shadowrocket_base(groups),
        ROOT / "Stash" / "Overrides" / "all.stoverride": yaml_text(all_stash_override(groups)),
        ROOT / "Clash-Verge" / "merge.yaml": yaml_text(clash_merge(groups)),
        ROOT / "Clash-Verge" / "snippets" / "groups.yaml": yaml_text(
            {
                "prepend": selectable_groups(groups, "clash"),
                "append": [],
                "delete": [],
            }
        ),
        ROOT / "Clash-Verge" / "snippets" / "rules.yaml": yaml_text(
            {
                "prepend": [rule for group in groups for rule in clash_rules(group)],
                "append": [],
                "delete": [],
            }
        ),
    }
    for group in groups:
        outputs[ROOT / "Shadowrocket" / "Modules" / f"{group['id']}.module"] = (
            render_shadowrocket_module(group)
        )
        outputs[ROOT / "Stash" / "Overrides" / f"{group['id']}.stoverride"] = yaml_text(
            stash_override(group)
        )
        outputs[ROOT / "Clash-Verge" / "snippets" / f"{group['id'].lower()}.yaml"] = yaml_text(
            clash_bundle(group),
            header=(
                f"{GENERATED_HEADER}\n"
                "# Clash Verge Rev v2.5.1 bundle: paste each child mapping "
                "into its matching editor."
            ),
        )
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    stale: list[Path] = []
    for path, content in expected_outputs().items():
        normalized = content.rstrip() + "\n"
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != normalized:
                stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(normalized, encoding="utf-8")

    if stale:
        print("Generated files are stale:", file=sys.stderr)
        for path in stale:
            print(f"  - {path}", file=sys.stderr)
        print("Run: python3 Scripts/build_configs.py", file=sys.stderr)
        return 1
    if args.check:
        print("Generated files are up to date.")
    else:
        print(f"Generated {len(expected_outputs())} files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
